version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
      - javascript
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions
